export const SERVICE_METHODS = {
  hasPermission: 'auth',
  hasGlobalPermission: 'auth',

  // Collab service methods
  connect: 'collab',
  disconnect: 'collab',
  isConnected: 'collab',
  updateData: 'collab',
  addItem: 'collab',
  addMultipleItems: 'collab',
  updateItem: 'collab',
  deleteItem: 'collab',
  undo: 'collab',
  redo: 'collab',
  checkpoint: 'collab',

  // Realtime collaboration helper methods
  sendCursor: 'collab',
  sendPresence: 'collab',
  toggleLive: 'collab',

  // Core service methods (new - replaces most based/auth functionality)
  // Auth methods
  getStoredAuthState: 'auth',
  getAuthToken: 'auth',
  register: 'auth',
  login: 'auth',
  logout: 'auth',
  refreshToken: 'auth',
  googleAuth: 'auth',
  googleAuthCallback: 'auth',
  githubAuth: 'auth',
  requestPasswordReset: 'auth',
  confirmPasswordReset: 'auth',
  confirmRegistration: 'auth',
  requestPasswordChange: 'auth',
  confirmPasswordChange: 'auth',
  getMe: 'auth',
  getTokenDebugInfo: 'auth',

  getMyProjectRoleByKey: 'auth',
  getProjectRoleWithFallback: 'auth',
  getProjectRoleByKeyWithFallback: 'auth',

  // User methods
  getUserProfile: 'auth',
  updateUserProfile: 'auth',
  getUserProjects: 'auth',
  getUser: 'auth',
  getUserByEmail: 'auth',

  // Project methods (moved to project service)
  createProject: 'project',
  getProjects: 'project',
  getProject: 'project',
  getProjectByKey: 'project',
  getProjectDataByKey: 'project',
  getPublicProjectDataByKey: 'project',
  getPublicProject: 'project',
  listPublicProjects: 'project',
  listProjects: 'project',
  updateProject: 'project',
  updateProjectComponents: 'project',
  updateProjectSettings: 'project',
  updateProjectName: 'project',
  updateProjectPackage: 'project',
  duplicateProject: 'project',
  removeProject: 'project',
  transferProjectOwnership: 'project',
  checkProjectKeyAvailability: 'project',
  getProjectRolePermissionsConfig: 'project',
  updateProjectRolePermissionsConfig: 'project',
  listEnvironments: 'project',
  upsertEnvironment: 'project',
  updateEnvironment: 'project',
  publishToEnvironment: 'project',
  deleteEnvironment: 'project',
  promoteEnvironment: 'project',

  // Project member methods (moved to project service)
  getProjectMembers: 'project',
  inviteMember: 'project',
  acceptInvite: 'project',
  createMagicInviteLink: 'project',
  updateMemberRole: 'project',
  removeMember: 'project',

  // Project library methods (moved to project service)
  getAvailableLibraries: 'project',
  getProjectLibraries: 'project',
  addProjectLibraries: 'project',
  removeProjectLibraries: 'project',

  // Project data methods (moved to project service)
  applyProjectChanges: 'project',
  getProjectData: 'project',
  getProjectVersions: 'project',
  restoreProjectVersion: 'project',
  updateProjectItem: 'project',
  deleteProjectItem: 'project',
  setProjectValue: 'project',
  addProjectItems: 'project',
  getProjectItemByPath: 'project',
  setProjectAccess: 'project',
  setProjectVisibility: 'project',

  // Favorite project methods (moved to project service)
  getFavoriteProjects: 'project',
  addFavoriteProject: 'project',
  removeFavoriteProject: 'project',

  // Recent project methods (moved to project service)
  getRecentProjects: 'project',

  // Plan methods (moved to plan service)
  getPlans: 'plan',
  getPlan: 'plan',
  getAdminPlans: 'plan',
  createPlan: 'plan',
  updatePlan: 'plan',
  deletePlan: 'plan',
  initializePlans: 'plan',
  getPlansWithValidation: 'plan',
  getPlanWithValidation: 'plan',
  createPlanWithValidation: 'plan',
  updatePlanWithValidation: 'plan',
  getActivePlans: 'plan',
  getPlansByPriceRange: 'plan',
  getPlanByKey: 'plan',
  getPlansWithPricing: 'plan',

  // Subscription methods (moved to subscription service)
  createSubscription: 'subscription',
  getProjectStatus: 'subscription',
  getUsage: 'subscription',
  cancelSubscription: 'subscription',
  listInvoices: 'subscription',
  getPortalUrl: 'subscription',
  createSubscriptionWithValidation: 'subscription',
  hasActiveSubscription: 'subscription',
  getProjectSubscription: 'subscription',
  getProjectUsage: 'subscription',
  getInvoicesWithPagination: 'subscription',
  isSubscriptionActive: 'subscription',
  getSubscriptionLimits: 'subscription',
  changeSubscription: 'subscription',
  downgrade: 'subscription',
  changeSubscriptionWithValidation: 'subscription',
  downgradeWithValidation: 'subscription',

  // File methods (moved to file service)
  uploadFile: 'file',
  updateProjectIcon: 'file',
  uploadFileWithValidation: 'file',
  uploadImage: 'file',
  uploadDocument: 'file',
  getFileUrl: 'file',
  validateFile: 'file',
  createFileFormData: 'file',
  uploadMultipleFiles: 'file',

  // Payment methods (Use subscription service instead)
  checkout: 'payment',
  getSubscriptionStatus: 'payment',
  checkoutWithValidation: 'payment',
  getSubscriptionStatusWithValidation: 'payment',
  getSubscriptionDetails: 'payment',
  checkoutForPlan: 'payment',
  checkoutForTeam: 'payment',
  validateSubscriptionStatus: 'payment',
  formatSubscriptionAmount: 'payment',
  getSubscriptionSummary: 'payment',

  // DNS methods (moved to dns service)
  createDnsRecord: 'dns',
  getDnsRecord: 'dns',
  removeDnsRecord: 'dns',
  getCustomHost: 'dns',
  addProjectCustomDomains: 'dns',
  validateDomain: 'dns',
  createDnsRecordWithValidation: 'dns',
  getDnsRecordWithValidation: 'dns',
  removeDnsRecordWithValidation: 'dns',
  addProjectCustomDomainsWithValidation: 'dns',
  isDomainAvailable: 'dns',
  getDomainStatus: 'dns',
  verifyDomainOwnership: 'dns',
  getProjectDomains: 'dns',
  removeProjectCustomDomain: 'dns',
  formatDomain: 'dns',
  extractDomainFromUrl: 'dns',

  // Branch Management methods (moved to branch service)
  listBranches: 'branch',
  createBranch: 'branch',
  deleteBranch: 'branch',
  renameBranch: 'branch',
  getBranchChanges: 'branch',
  mergeBranch: 'branch',
  resetBranch: 'branch',
  publishVersion: 'branch',
  createBranchWithValidation: 'branch',
  branchExists: 'branch',
  previewMerge: 'branch',
  commitMerge: 'branch',
  createFeatureBranch: 'branch',
  createHotfixBranch: 'branch',
  getBranchStatus: 'branch',
  deleteBranchSafely: 'branch',
  getBranchesWithStatus: 'branch',
  validateBranchName: 'branch',
  sanitizeBranchName: 'branch',

  // Pull Request methods (moved to pullRequest service)
  createPullRequest: 'pullRequest',
  listPullRequests: 'pullRequest',
  getPullRequest: 'pullRequest',
  reviewPullRequest: 'pullRequest',
  addPullRequestComment: 'pullRequest',
  mergePullRequest: 'pullRequest',
  getPullRequestDiff: 'pullRequest',
  createPullRequestWithValidation: 'pullRequest',
  approvePullRequest: 'pullRequest',
  requestPullRequestChanges: 'pullRequest',
  getOpenPullRequests: 'pullRequest',
  getClosedPullRequests: 'pullRequest',
  getMergedPullRequests: 'pullRequest',
  isPullRequestMergeable: 'pullRequest',
  getPullRequestStatusSummary: 'pullRequest',
  validatePullRequestData: 'pullRequest',
  validateReviewData: 'pullRequest',
  getPullRequestStats: 'pullRequest',
  closePullRequest: 'pullRequest',
  reopenPullRequest: 'pullRequest',

  // Admin methods (moved to admin service)
  getAdminUsers: 'admin',
  assignProjectsToUser: 'admin',
  updateUser: 'admin',
  searchAdminUsers: 'admin',
  getAdminUsersByEmails: 'admin',
  getAdminUsersByIds: 'admin',
  assignSpecificProjectsToUser: 'admin',
  assignAllProjectsToUser: 'admin',
  validateUserData: 'admin',
  updateUserWithValidation: 'admin',
  getUserStats: 'admin',
  bulkUpdateUsers: 'admin',
  getUsersByRole: 'admin',
  getUsersByStatus: 'admin',
  activateUser: 'admin',
  deactivateUser: 'admin',
  suspendUser: 'admin',
  promoteToAdmin: 'admin',
  demoteFromAdmin: 'admin',

  // Screenshot methods
  createScreenshotProject: 'screenshot',
  getProjectScreenshots: 'screenshot',
  reprocessProjectScreenshots: 'screenshot',
  recreateProjectScreenshots: 'screenshot',
  deleteProjectScreenshots: 'screenshot',
  getThumbnailCandidate: 'screenshot',
  updateProjectThumbnail: 'screenshot',
  getPageScreenshot: 'screenshot',
  getComponentScreenshot: 'screenshot',
  getScreenshotByKey: 'screenshot',
  getQueueStatistics: 'screenshot',
  refreshThumbnail: 'screenshot',

  // Tracking methods
  configureTracking: 'tracking',
  trackEvent: 'tracking',
  trackError: 'tracking',
  captureException: 'tracking',
  logMessage: 'tracking',
  logDebug: 'tracking',
  logInfo: 'tracking',
  logWarning: 'tracking',
  logWarn: 'tracking',
  logErrorMessage: 'tracking',
  logError: 'tracking',
  addBreadcrumb: 'tracking',
  trackMeasurement: 'tracking',
  trackView: 'tracking',
  setUser: 'tracking',
  clearUser: 'tracking',
  setSession: 'tracking',
  clearSession: 'tracking',
  setGlobalAttributes: 'tracking',
  setGlobalAttribute: 'tracking',
  removeGlobalAttribute: 'tracking',
  flushQueue: 'tracking',
  getClient: 'tracking',
  isEnabled: 'tracking',
  isInitialized: 'tracking',

  // Waitlist methods
  joinWaitlist: 'waitlist',
  listWaitlistEntries: 'waitlist',
  updateWaitlistEntry: 'waitlist',
  inviteWaitlistEntry: 'waitlist',

  // Metrics methods
  getContributions: 'metrics',

  // Integration methods
  integrationWhoami: 'integration',
  listIntegrations: 'integration',
  createIntegration: 'integration',
  updateIntegration: 'integration',
  createIntegrationApiKey: 'integration',
  listIntegrationApiKeys: 'integration',
  revokeIntegrationApiKey: 'integration',
  createIntegrationWebhook: 'integration',
  listIntegrationWebhooks: 'integration',
  updateIntegrationWebhook: 'integration',
  deleteIntegrationWebhook: 'integration',
  listIntegrationWebhookDeliveries: 'integration',
  replayIntegrationWebhookDelivery: 'integration',
  listGitHubConnectors: 'integration',
  createGitHubConnector: 'integration',
  updateGitHubConnector: 'integration',
  deleteGitHubConnector: 'integration',

  // Feature flag methods (system-level + experiments)
  getFeatureFlags: 'featureFlag',
  getFeatureFlag: 'featureFlag',
  getAdminFeatureFlags: 'featureFlag',
  createFeatureFlag: 'featureFlag',
  updateFeatureFlag: 'featureFlag',
  archiveFeatureFlag: 'featureFlag',

  // Organization methods
  createOrganization: 'organization',
  listOrganizations: 'organization',
  getOrganization: 'organization',
  updateOrganization: 'organization',
  transferOrgOwnership: 'organization',
  deleteOrganization: 'organization',
  listOrgMembers: 'organization',
  addOrgMember: 'organization',
  updateOrgMember: 'organization',
  removeOrgMember: 'organization',
  createTeam: 'organization',
  listTeams: 'organization',
  updateTeam: 'organization',
  deleteTeam: 'organization',
  listTeamMembers: 'organization',
  addTeamMember: 'organization',
  updateTeamMember: 'organization',
  removeTeamMember: 'organization',
  createOrgInvitation: 'organization',
  listOrgInvitations: 'organization',
  revokeOrgInvitation: 'organization',
  acceptOrgInvitation: 'organization',
  getOrgProjectPermissions: 'organization',
  updateOrgProjectPermissions: 'organization',
  listTeamAccess: 'organization',
  grantTeamAccess: 'organization',
  updateTeamAccess: 'organization',
  revokeTeamAccess: 'organization',
  createOrgProject: 'organization',
  adminListOrganizations: 'organization',

  createWorkspace: 'workspace',
  listWorkspaces: 'workspace',
  getWorkspace: 'workspace',
  updateWorkspace: 'workspace',
  deleteWorkspace: 'workspace',
  listWorkspaceMembers: 'workspace',
  addWorkspaceMember: 'workspace',
  updateWorkspaceMemberRole: 'workspace',
  removeWorkspaceMember: 'workspace',
  grantWorkspaceTeamAccess: 'workspace',
  revokeWorkspaceTeamAccess: 'workspace',
  getBilling: 'workspace',
  getCreditBalance: 'workspace',
  getCreditLedger: 'workspace',
  getSpendControls: 'workspace',
  updateSpendControls: 'workspace',
  setProjectSourceAccess: 'project'
}
