name: Pull Request Tests Workflow
on:
  workflow_dispatch:
  repository_dispatch:
    types: [run_smoke_tests]
  pull_request:
    branches:
     - next
    paths:
    - 'src/**'
    - 'integration-tests/**'
    - 'package.json'

jobs:
  smoke-tests:
    uses: ./.github/workflows/test-workflow.yaml
    with:
      node_env: 'testing'
      suite: 'smoke'
    secrets: inherit
