name: Scheduled Tests Workflow
on:
  repository_dispatch:
    types: [run_sdk_tests]
  workflow_dispatch:
  schedule:
    - cron: '0 9 * * *'

jobs:
  scheduled-tests:
    uses: ./.github/workflows/test-workflow.yaml
    with:
      node_env: 'testing'
      suite: 'project'
    secrets: inherit
