name: Test
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
concurrency:
  group: test-${{ github.ref }}
  cancel-in-progress: true
jobs:
  test:
    uses: symbo-ls/release-manager/.github/workflows/test-reusable.yml@main
    secrets: inherit
